language: php

php:
  - 7.1
  - 7.2

services:
  - mysql


sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_install:
- mysql -u root -e 'CREATE DATABASE teste_ingresse;'

install: travis_retry composer install --no-interaction --prefer-source

script: 
  - php artisan migrate
  - php artisan db:seed
  - phpvendor/bin/phpunit