language: php

php: 7.2

services:
  - mysql


sudo: required

addons:
  apt:
    packages:
    - mysql-server-5.6
    - mysql-client-core-5.6
    - mysql-client-5.6
before_script:
  - cp .env.travis .env
  - mysql -u root -e 'CREATE DATABASE teste_ingresse;'

install: travis_retry composer install --no-interaction --prefer-source

script: 
  - ./web/artisan migrate
  - ./web/artisan db:seed
  - ./web/vendor/bin/phpunit

after_success:
  - bash <(curl -s https://codecov.io/bash)