version: '3'
services:
    web:
        build: .
        container_name: app
        ports:
            - "8000:80"
        restart: on-failure
        links:
            - redis
        environment:
            - REDIS_URL=redis://cache
            - MYSQL_HOST=${MYSQL_HOST}
        depends_on:
            - redis
            - mysqldb
            - myadmin 
        entrypoint: ["./scripts/run.sh"]
        tty: true
    redis:
        container_name: redis
        image: redis:alpine
        ports:
            - "6379"
        tty: true
        
    myadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - "8080:80"
        environment:
            - PMA_ARBITRARY=1
            - PMA_HOST=${MYSQL_HOST}
        restart: always
        depends_on:
            - mysqldb
        tty: true
    mysqldb:
        image: mysql:${MYSQL_VERSION}
        container_name: ${MYSQL_HOST}
        restart: always
        env_file:
            - ".env"
        environment:
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
            - MYSQL_ALLOW_EMPTY_PASSWORD=true
        ports:
            - "8989:3306"
        volumes:
            - "./data/db/mysql:/var/lib/mysql"
        tty: true